Repository Zaai90/GaG-App, pull requests merged in 2022-09, with the labels that each got.

#16 Update README
  README.md
Labels: G

#25 PlayThisScreen added
  src/Screens/PlayThis.tsx
  src/navigation/HomeStack.tsx
  src/navigation/Types.ts
Labels: G

#26 Added Play this favorite game screen
  src/Screens/PlayThisFavorite.tsx
  src/navigation/HomeStack.tsx
  src/navigation/Types.ts
Labels: Extra feature

#29 Added settings screen
  src/Screens/Settings.tsx
  src/navigation/HomeStack.tsx
Labels: Extra feature

#39 Added eslint and prettier rules
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  App.tsx
  app.json
  babel.config.js
  package-lock.json
  package.json
  src/Screens/Add.tsx
  src/Screens/Edit.tsx
  src/Screens/FavGameList.tsx
  src/Screens/GameList.tsx
  src/Screens/Home.tsx
  src/Screens/PlayThis.tsx
  src/Screens/PlayThisFav.tsx
  src/Screens/Settings.tsx
  src/navigation/HomeStack.tsx
  src/navigation/index.tsx
Labels: enhancement

#42 hotfix eslint issues
  App.tsx
  src/Screens/PlayThis.tsx
  src/Screens/Settings.tsx
  src/navigation/HomeStack.tsx
Labels: Hotfix

#45 add game type
  src/Data/Game.ts
Labels: good first issue

#68 66 change mockdata from json to ts
  src/Data/MockData.json
  src/Data/MockData.ts
  src/navigation/Types.ts
Labels: Hotfix

#73 update name prop to to
  src/Screens/Home.tsx
Labels: Hotfix

#76 hotfix problems
  src/Screens/GameList.tsx
  src/Screens/Home.tsx
  src/components/GotoButton.tsx
Labels: bug

#77 63 create context for the games 1
  App.tsx
  src/Components1/GameCard.tsx
  src/Components1/GotoButton.tsx
  src/Components1/HomeButton.tsx
  src/Context/GameContext.tsx
  src/Data/Game.ts
  src/Data/MockData.ts
  src/Screens/GameList.tsx
  src/Screens/Home.tsx
  src/navigation/Index1.tsx
Labels: G

#79 changed name on Index file and Component folder
  App.tsx
  src/Components/GameCard.tsx
  src/Components/GotoButton.tsx
  src/Components/HomeButton.tsx
  src/Screens/GameList.tsx
  src/Screens/Home.tsx
  src/navigation/Index.tsx
Labels: Hotfix

#88 GameList is now using GameContext
  App.tsx
  package-lock.json
  package.json
  src/Context/GameContext.tsx
  src/Screens/GameList.tsx
Labels: Hotfix

#90 add imgurl prop to game, show pic in gamecard
  src/Components/GameCard.tsx
  src/Data/game.ts
  src/Data/mockData.ts
Labels: Extra feature

#99 91 1 add functionality to playthis screen
  package-lock.json
  package.json
  src/Components/GAGCard.tsx
  src/Components/GetAGame.tsx
  src/Screens/PlayThis.tsx
Labels: G

#103 83 design the gamecard
  src/Components/GameCard.tsx
  src/Screens/GameList.tsx
Labels: G

#105 Hotfix
  src/Components/GameCard.tsx
  src/Screens/GameList.tsx
Labels: G

#115 add as favorite now works and heart becomes filled
  src/Components/GameCard.tsx
  src/Context/GameContext.tsx
  src/Data/mockData.ts
Labels: G
