Repository Zaai90/GaG-App, pull requests merged in 2022-10, with the labels that each got.

#124 Change speech settings to english
  app.json
  src/Components/Speech.tsx
Labels: bug

#128 118 add sound effect to gaggagafav buttons
  assets/DeathSoundEffect.wav
  assets/quickFixes.mp3
  package-lock.json
  package.json
  src/Components/GetAFav.tsx
  src/Components/GetAGame.tsx
  src/Components/SoundButton.tsx
  src/audio.d.ts
Labels: component

#130 icon for text to speech and center it in play this
  src/Components/GetAGame.tsx
  src/Components/Speech.tsx
Labels: design

#142 126 2 animate game image
  src/Components/AnimView.tsx
  src/Components/GetAFav.tsx
  src/Components/GetAGame.tsx
  src/Screens/Home.tsx
Labels: G

#145 140 implement haptics settings on buttons
  src/Components/Speech.tsx
  src/Screens/Settings.tsx
Labels: bug

#153 152 go through update readme
  Figma.png
  README.md
  src/Components/Header/HomeButton.tsx
Labels: documentation

#154 fixes
  package-lock.json
  src/Components/Buttons/SoundButton.tsx
Labels: bug

#156 Add nav to Editpage
  src/Components/GameCard.tsx
  src/Screens/Edit.tsx
Labels: Extra feature

#160 remove 1 useGameContext
  src/Components/GetAGame.tsx
Labels: Hotfix

#164 Fix AddGame, Credit to Erik & Lukas
  package-lock.json
  package.json
  src/Components/Buttons/GotoButton.tsx
  src/Components/GameCard.tsx
  src/Context/GameContext.tsx
  src/Screens/Add.tsx
  src/Screens/GameList.tsx
Labels: Extra feature

#165 delete button now deletes games, GaG me hidden if there are no games
  src/Components/GameCard.tsx
  src/Screens/Home.tsx
Labels: Extra feature
